#!/usr/bin/env python3
"""UI check of Connections + the connection source of the Auto-Loader dialog (Playwright, /usr/bin/python3) against a THROWAWAY studio
(admin/adminpassword123) on a docker network with a file server `gtesthttp:8000` (serving /data.csv) and an SFTP server `gtestsftp`
(user/pass):  GIT_UI_URL=http://localhost:8117 python scratch/verify_connections_ui.py"""
import os, sys, time
from playwright.sync_api import sync_playwright
BASE = os.getenv("GIT_UI_URL", "http://localhost:8117").rstrip("/")
FAIL = []
def check(n, c, d=""):
    print(f"  [{'PASS' if c else 'FAIL'}] {n}" + (f" -> {str(d)[:300]}" if d and not c else ""))
    if not c: FAIL.append(n)
with sync_playwright() as p:
    b = p.chromium.launch(); ctx = b.new_context(viewport={"width": 1500, "height": 1200}); page = ctx.new_page()
    errs = []; page.on("pageerror", lambda e: errs.append(str(e)))
    check("login", ctx.request.post(f"{BASE}/api/auth/login", data={"username": "admin", "password": "adminpassword123"}).ok)
    page.goto(BASE, wait_until="networkidle"); time.sleep(1)
    page.evaluate("async () => { const d = Alpine.$data(document.body); d.currentView = 'autoloader'; await d.fetchAutoloaderPipelines(); }")
    page.locator("[data-testid=open-connections]:visible").click()
    m = page.locator("[data-testid=connections-modal]:visible"); m.wait_for(timeout=8000)
    # --- http connection
    m.locator("[data-testid=conn-new]").click()
    m.locator("[data-testid=conn-name]").fill("files"); m.locator("[data-testid=conn-base-url]").fill("http://gtesthttp:8000")
    m.locator("[data-testid=conn-auth]").select_option("bearer")
    m.locator("[data-testid=conn-secret]").fill("tok-123")
    m.locator("text=Allow credentials over plain http").click()
    m.locator("[data-testid=conn-test]").click(); m.locator("[data-testid=conn-test-result]").wait_for(timeout=15000)
    check("Test reaches the file server", "Reached gtesthttp" in m.locator("[data-testid=conn-test-result]").inner_text(), m.locator("[data-testid=conn-test-result]").inner_text())
    m.locator("[data-testid=conn-save]").click(); m.locator("[data-testid=conn-row]").first.wait_for(timeout=8000)
    check("connection listed with a stored secret", "files" in m.inner_text() and "stored" in m.inner_text())
    check("the secret is nowhere in the page", "tok-123" not in page.content())
    api = ctx.request.get(f"{BASE}/api/connections").text()
    check("the API never returns the secret", "tok-123" not in api and '"has_secret":true' in api.replace(" ", ""))
    # --- sftp connection: fingerprint flow
    m.locator("[data-testid=conn-new]").click()
    m.locator("[data-testid=conn-name]").fill("sftpbox"); m.locator("[data-testid=conn-type]").select_option("sftp")
    m.locator("[data-testid=conn-host]").fill("gtestsftp"); m.locator("[data-testid=conn-user]").fill("user"); m.locator("[data-testid=conn-sftp-password]").fill("pass")
    m.locator("[data-testid=conn-save]").click(); m.locator("[data-testid=conn-error]").wait_for(timeout=8000)
    check("saving SFTP without a fingerprint is refused", "fingerprint" in m.locator("[data-testid=conn-error]").inner_text())
    m.locator("[data-testid=conn-test]").click(); m.locator("[data-testid=conn-pin]").wait_for(timeout=20000)
    check("Test shows the fingerprint to verify", "SHA256:" in m.locator("[data-testid=conn-test-result]").inner_text())
    m.locator("[data-testid=conn-pin]").click()
    check("Pin fills the field", m.locator("[data-testid=conn-fingerprint]").input_value().startswith("SHA256:"))
    m.locator("[data-testid=conn-test]").click(); time.sleep(3)
    check("Test with the pinned key succeeds", "login works" in m.locator("[data-testid=conn-test-result]").inner_text(), m.locator("[data-testid=conn-test-result]").inner_text())
    m.locator("[data-testid=conn-save]").click(); time.sleep(1.5)
    check("both connections listed", m.locator("[data-testid=conn-row]").count() == 2, m.locator("[data-testid=conn-row]").count())
    page.screenshot(path="/tmp/connections_ui.png")
    page.keyboard.press("Escape")
    # --- pipeline dialog with a connection source
    page.evaluate("() => { Alpine.$data(document.body).showConnectionsModal = false; Alpine.$data(document.body).showCreatePipelineModal = true; }")
    page.locator("[data-testid=src-connection]:visible").click()
    src = page.locator("[data-testid=conn-source]:visible"); src.wait_for(timeout=5000); time.sleep(0.8)
    check("the connection dropdown lists both", src.locator("[data-testid=pipe-conn] option").count() == 3)
    src.locator("[data-testid=pipe-conn]").select_option("files"); src.locator("[data-testid=pipe-conn-path]").fill("data.csv"); time.sleep(0.5)
    check("http: file/API choice shown", src.locator("[data-testid=pipe-mode-api]").is_visible())
    src.locator("[data-testid=pipe-mode-api]").check(); time.sleep(0.5)
    check("REST options appear", src.locator("[data-testid=pipe-records-path]").is_visible())
    src.locator("[data-testid=pipe-mode-file]").check()
    check("file format dropdown hidden for an HTTP source", not page.locator("[data-testid=pipeline-format]:visible").count())
    src.locator("[data-testid=pipe-preview]").click(); src.locator("[data-testid=pipe-preview-table]").wait_for(timeout=15000); time.sleep(0.5)
    tbl = src.locator("[data-testid=pipe-preview-table]").inner_text()
    check("Preview shows the file's columns (with types) and its first rows, before any pipeline exists", "id" in tbl and "v" in tbl and "3 row(s) shown" in src.inner_text() and "there are more" not in src.inner_text(), tbl)
    check("...and created nothing", not [x for x in ctx.request.get(f"{BASE}/api/autoloader/pipelines").json()["pipelines"] if x["name"] == "ui http"])
    src.locator("[data-testid=pipe-conn-path]").fill("nope.csv"); src.locator("[data-testid=pipe-preview]").click(); src.locator("[data-testid=pipe-preview-error]").wait_for(timeout=10000)
    check("a bad path is explained in the dialog", "Not found" in src.locator("[data-testid=pipe-preview-error]").inner_text(), src.locator("[data-testid=pipe-preview-error]").inner_text())
    src.locator("[data-testid=pipe-conn-path]").fill("data.csv")
    src.locator("[data-testid=pipe-mode-api]").check(); src.locator("[data-testid=pipe-preview]").click(); src.locator("[data-testid=pipe-preview-error]").wait_for(timeout=10000); time.sleep(0.3)
    check("REST mode against a non-JSON response is explained", "JSON" in src.locator("[data-testid=pipe-preview-error]").inner_text() or "records" in src.locator("[data-testid=pipe-preview-error]").inner_text(), src.locator("[data-testid=pipe-preview-error]").inner_text())
    src.locator("[data-testid=pipe-mode-file]").check()
    src.locator("[data-testid=pipe-conn]").select_option("sftpbox"); time.sleep(0.5)
    check("changing the connection clears the preview", not src.locator("[data-testid=pipe-preview-table]").is_visible())
    check("sftp: file format dropdown and folder options shown", page.locator("[data-testid=pipeline-format]:visible").count() == 1 and src.locator("text=Include sub-folders").is_visible())
    src.locator("[data-testid=pipe-conn]").select_option("files")
    body = page.evaluate("() => { const d = Alpine.$data(document.body); d.newPipelineForm.name = 'ui http'; d.newPipelineForm.target_table = 'ui_http'; return d.connSourceForSubmit(); }")
    check("composed source is conn://files/data.csv (file mode)", body["source_volume_path"] == "conn://files/data.csv" and body["source_options"] == {"mode": "file"}, body)
    page.evaluate("async () => { await Alpine.$data(document.body).createAutoloaderPipelineSubmit(); }")
    time.sleep(1.5)
    pipes = ctx.request.get(f"{BASE}/api/autoloader/pipelines").json()["pipelines"]
    pipe = next((x for x in pipes if x["name"] == "ui http"), None)
    check("the pipeline was created with the connection source", pipe is not None and pipe["source_volume_path"] == "conn://files/data.csv" and pipe["source_options"] == {"mode": "file"}, pipe)
    if pipe:
        ctx.request.post(f"{BASE}/api/autoloader/pipelines/{pipe['id']}/run-now")      # (the background daemon may have run it first: the file is loaded once either way)
        for _ in range(15):
            cur = next(x for x in ctx.request.get(f"{BASE}/api/autoloader/pipelines").json()["pipelines"] if x["id"] == pipe["id"])
            if cur["total_files_ingested"]: break
            time.sleep(1)
        check("the file was loaded from the server exactly once (3 rows)", cur["total_files_ingested"] == 1 and cur["total_rows_ingested"] == 3 and not cur["last_error"], cur)
    check("no page errors", not errs, errs)
    b.close()
print("FAILED: " + ", ".join(FAIL) if FAIL else "ALL PASS"); sys.exit(1 if FAIL else 0)
